### PR TITLE
Configure Behat integration tests to run in CircleCI

### LINKED ISSUE #19: Add CircleCI/Pantheon tests
If development on this plugin resumes, we should add tests in the same pattern as other Pantheon-maintained WordPress plugins:

- https://github.com/pantheon-systems/wp-native-php-sessions/blob/master/circle.yml
- https://github.com/pantheon-systems/wp-redis/blob/master/circle.yml
- https://github.com/pantheon-systems/solr-power/blob/master/circle.yml

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #19

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@ataylorme @stevector I think I'll need your help to get this running, specifically:

* [ ] The project needs to be followed in CircleCI so we start getting builds.
* [ ] Whichever Pantheon user we've been using for auth needs to be added to https://dashboard.pantheon.io/sites/862f5893-4854-4f57-8958-6148afc33aaf
* [ ] Environment variables need to be configured (including, but not limited to, `$GITHUB_TOKEN` and `$TERMINUS_TOKEN`.
* [ ] Circle should be set to run on a nightly cron.

Let me know when you might be able to get to it. Thanks!

**Comment by ataylorme** [comment]
@danielbachhuber the project has been set up on CircleCI. I will look at adding environment variables later this week once I track down the bot user used elsewhere.

**Comment by ataylorme** [comment]
@danielbachhuber @greg-1-anderson and I are working on the credentials.

Running CircleCI on a cron is not a project setting but rather configured in `.circle.yml` and something you can add with this PR. See [their workflow documentation](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow) for details.

**Comment by ataylorme** [comment]
@danielbachhuber `GITHUB_TOKEN` and `PANTHEON_TOKEN` have been added as CircleCI environment variables. Please test your scripts.

**Comment by danielbachhuber** [comment]
@ataylorme Looks like the `git clone` operation is stuck on the password prompt:

image

I think we need to generate a SSH key for CircleCI and add it to the SSH keys for the Pantheon bot account?

**Comment by ataylorme** [comment]
> I think we need to generate an SSH key for CircleCI and add it to the SSH keys for the Pantheon bot account

That sounds right. I think @greg-1-anderson will need to do this since we used one of his bot accounts.

**Comment by greg-1-anderson** [comment]
CircleCI is letting me in to the settings section now so I can do that.

**Comment by danielbachhuber** [comment]
@greg-1-anderson Any luck getting a SSH key configured?

**Comment by greg-1-anderson** [comment]
Last week was busy, and I forgot. Just added ssh keys and re-started the build; it got a bit farther, looks like the ssh key is working now.

**Comment by danielbachhuber** [comment]
Thanks @greg-1-anderson ! Good to go now 😄 

@ataylorme @stevector Are you using some third-party service to trigger nightly builds [using the webhook approach](https://circleci.com/docs/2.0/triggers/#trigger-a-job-using-curl-and-your-api-token) on the other repos? Should we keep using that for this repo too, or should we switch over to [CircleCI scheduled builds](https://circleci.com/docs/2.0/triggers/#scheduled-builds)?

**Comment by ataylorme** [comment]
@danielbachhuber scheduled builds are the way to go

**Comment by ataylorme** [comment]
@danielbachhuber can you set up two workflows, both of which run the Behat job? I think the Behat tests should be run on pull requests and `master` builds in addition to being run nightly on `master` to help mitigate regressions.

**Comment by danielbachhuber** [comment]
@ataylorme Isn't that what I did with ffd251a5140337edbc569e47ce11e5e87a8432ae ?

**Comment by ataylorme** [comment]
@danielbachhuber ah, I misread the config. I see there is a `main` and a `nightly` workflow 🎉

**Pull request merged**
