### PR TITLE
add jazzsequence/action-validate-plugin-version

### PR DESCRIPTION
**Pull request by jazzsequence**
Adds [`jazzsequence/action-validate-plugin-version`](https://github.com/jazzsequence/action-validate-plugin-version) to regularly check the tested-up-to version

### CODE REVIEW

**Comment by pwtyler** [comment]
Prefer to fix [this](https://github.com/jazzsequence/action-validate-plugin-version/issues/11) and also is behat test a random failure?

**Comment by jazzsequence** [comment]
@pwtyler Behat is failing because the tested up to version is wrong. See #149

**Comment by jazzsequence** [comment]
@pwtyler bug is fixed, see https://github.com/pantheon-systems/plugin-pipeline-example/pull/91/files

**Comment by pwtyler** [comment]
> @pwtyler Behat is failing because the tested up to version is wrong. See https://github.com/pantheon-systems/pantheon-hud/pull/149

Ah I got my wires crossed, 149 is failing due to actual feature failures.

**Review by pwtyler — APPROVED** [review]

**Comment by jazzsequence** [comment]
merging #149 into this, so these tests will pass, too

**Review by namespacebrian — APPROVED** [review]

**Review by pwtyler — APPROVED** [review]

**Pull request merged**
